# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Blog Post Workflow
      uses: gautamkrishnar/blog-post-workflow@1.0.4
      with:
          # GitHub access token with Repo scope
          gh_token:  ${{ github.token }}
          # Path of the readme file you want to update
          readme_path: ./README.md
          # Maximum number of posts you want to show on your readme, all feeds combined
          max_post_count:  5
          # Comma separated list of RSS feed urls
          feed_list: https://medium.com/feed/@sachushajiabraham
          # Override the default comment tag name, if you want to show multiple instances of the action on the same repo
          comment_tag_name: "MEDIUM"
      
